resources:
- kyma-installer-cluster.yaml

patchesJSON6902:
- target:
    group: installer.kyma-project.io
    version: v1alpha1
    kind: Installation
    name: kyma-installation
  patch: |-
    - op: replace
      path: /spec/components
      value: 
        - name: "cluster-essentials"
          namespace: "kyma-system"
        - name: "testing"
          namespace: "kyma-system"
        - name: "istio"
          namespace: "istio-system"
        - name: "xip-patch"
          namespace: "kyma-installer"
        - name: "istio-kyma-patch"
          namespace: "istio-system"
        - name: "dex"
          namespace: "kyma-system"
        - name: "logging"
          namespace: "kyma-system"
        - name: "backup-init"
          namespace: "kyma-system"
        - name: "backup"
          namespace: "kyma-system"
        - name: "tracing"
          namespace: "kyma-system"
        - name: "monitoring"
          namespace: "kyma-system"
        - name: "kiali"
          namespace: "kyma-system"